[package]
name = "rust-parser"
version = "0.1.0"
authors = ["KikoPT1234 <carricokiko2006@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.8.4"